module.exports = [
    {
        name: "Água Verde",
        image: "./assets/stores/store-01.jpg",
        phone: "(41) 3343-2222",
        address: "Avenida Água Verde, 470",
        email: "aguaverde@tintasverginia.com.br",
        timer_title: "Horário de atendimento:",
        timer: "Segunda a Sexta das 08h às 18h <br />Sábado das 08h às 13h",
    },
    {
        name: "Ahú",
        image: "./assets/stores/store-02.jpg",
        phone: "(41) 3343-2222",
        address: "Avenida Água Verde, 470",
        email: "aguaverde@tintasverginia.com.br",
        timer_title: "Horário de atendimento:",
        timer: "Segunda a Sexta das 08h às 18h <br />Sábado das 08h às 13h",
    },
    {
        name: "Alto da XV",
        image: "./assets/stores/store-03.jpg",
        phone: "(41) 3343-2222",
        address: "Avenida Água Verde, 470",
        email: "aguaverde@tintasverginia.com.br",
        timer_title: "Horário de atendimento:",
        timer: "Segunda a Sexta das 08h às 18h <br />Sábado das 08h às 13h",
    },
    {
        name: "Araucária",
        image: "./assets/stores/store-04.jpg",
        phone: "(41) 3343-2222",
        address: "Avenida Água Verde, 470",
        email: "aguaverde@tintasverginia.com.br",
        timer_title: "Horário de atendimento:",
        timer: "Segunda a Sexta das 08h às 18h <br />Sábado das 08h às 13h",
    },
    {
        name: "Bacacheri",
        image: "./assets/stores/store-05.jpg",
        phone: "(41) 3343-2222",
        address: "Avenida Água Verde, 470",
        email: "aguaverde@tintasverginia.com.br",
        timer_title: "Horário de atendimento:",
        timer: "Segunda a Sexta das 08h às 18h <br />Sábado das 08h às 13h",
    },
    {
        name: "Bom Retiro",
        image: "./assets/stores/store-06.jpg",
        phone: "(41) 3343-2222",
        address: "Avenida Água Verde, 470",
        email: "aguaverde@tintasverginia.com.br",
        timer_title: "Horário de atendimento:",
        timer: "Segunda a Sexta das 08h às 18h <br />Sábado das 08h às 13h",
    },
    {
        name: "Campo Largo",
        image: "./assets/stores/store-07.jpg",
        phone: "(41) 3343-2222",
        address: "Avenida Água Verde, 470",
        email: "aguaverde@tintasverginia.com.br",
        timer_title: "Horário de atendimento:",
        timer: "Segunda a Sexta das 08h às 18h <br />Sábado das 08h às 13h",
    },
    {
        name: "Capão Raso",
        image: "./assets/stores/store-08.jpg",
        phone: "(41) 3343-2222",
        address: "Avenida Água Verde, 470",
        email: "aguaverde@tintasverginia.com.br",
        timer_title: "Horário de atendimento:",
        timer: "Segunda a Sexta das 08h às 18h <br />Sábado das 08h às 13h",
    },
    {
        name: "Centro Cívico",
        image: "./assets/stores/store-09.jpg",
        phone: "(41) 3343-2222",
        address: "Avenida Água Verde, 470",
        email: "aguaverde@tintasverginia.com.br",
        timer_title: "Horário de atendimento:",
        timer: "Segunda a Sexta das 08h às 18h <br />Sábado das 08h às 13h",
    },
    {
        name: "Colombo",
        image: "./assets/stores/store-10.jpg",
        phone: "(41) 3343-2222",
        address: "Avenida Água Verde, 470",
        email: "aguaverde@tintasverginia.com.br",
        timer_title: "Horário de atendimento:",
        timer: "Segunda a Sexta das 08h às 18h <br />Sábado das 08h às 13h",
    },
    {
        name: "Fazenda Rio Grande",
        image: "./assets/stores/store-11.jpg",
        phone: "(41) 3343-2222",
        address: "Avenida Água Verde, 470",
        email: "aguaverde@tintasverginia.com.br",
        timer_title: "Horário de atendimento:",
        timer: "Segunda a Sexta das 08h às 18h <br />Sábado das 08h às 13h",
    },
    {
        name: "Hauer",
        image: "./assets/stores/store-12.jpg",
        phone: "(41) 3343-2222",
        address: "Avenida Água Verde, 470",
        email: "aguaverde@tintasverginia.com.br",
        timer_title: "Horário de atendimento:",
        timer: "Segunda a Sexta das 08h às 18h <br />Sábado das 08h às 13h",
    },
    {
        name: "Jardim das Américas",
        image: "./assets/stores/store-13.jpg",
        phone: "(41) 3343-2222",
        address: "Avenida Água Verde, 470",
        email: "aguaverde@tintasverginia.com.br",
        timer_title: "Horário de atendimento:",
        timer: "Segunda a Sexta das 08h às 18h <br />Sábado das 08h às 13h",
    },
    {
        name: "Londoia",
        image: "./assets/stores/store-14.jpg",
        phone: "(41) 3343-2222",
        address: "Avenida Água Verde, 470",
        email: "aguaverde@tintasverginia.com.br",
        timer_title: "Horário de atendimento:",
        timer: "Segunda a Sexta das 08h às 18h <br />Sábado das 08h às 13h",
    },
    {
        name: "Pinhais",
        image: "./assets/stores/store-15.jpg",
        phone: "(41) 3343-2222",
        address: "Avenida Água Verde, 470",
        email: "aguaverde@tintasverginia.com.br",
        timer_title: "Horário de atendimento:",
        timer: "Segunda a Sexta das 08h às 18h <br />Sábado das 08h às 13h",
    },
    {
        name: "Ponta Grossa",
        image: "./assets/stores/store-16.jpg",
        phone: "(41) 3343-2222",
        address: "Avenida Água Verde, 470",
        email: "aguaverde@tintasverginia.com.br",
        timer_title: "Horário de atendimento:",
        timer: "Segunda a Sexta das 08h às 18h <br />Sábado das 08h às 13h",
    },
    {
        name: "São Braz",
        image: "./assets/stores/store-17.jpg",
        phone: "(41) 3343-2222",
        address: "Avenida Água Verde, 470",
        email: "aguaverde@tintasverginia.com.br",
        timer_title: "Horário de atendimento:",
        timer: "Segunda a Sexta das 08h às 18h <br />Sábado das 08h às 13h",
    },
    {
        name: "São José dos Pinhais",
        image: "./assets/stores/store-18.jpg",
        phone: "(41) 3343-2222",
        address: "Avenida Água Verde, 470",
        email: "aguaverde@tintasverginia.com.br",
        timer_title: "Horário de atendimento:",
        timer: "Segunda a Sexta das 08h às 18h <br />Sábado das 08h às 13h",
    },
    {
        name: "Seminário",
        image: "./assets/stores/store-19.jpg",
        phone: "(41) 3343-2222",
        address: "Avenida Água Verde, 470",
        email: "aguaverde@tintasverginia.com.br",
        timer_title: "Horário de atendimento:",
        timer: "Segunda a Sexta das 08h às 18h <br />Sábado das 08h às 13h",
    },
    {
        name: "Tarumã",
        image: "./assets/stores/store-20.jpg",
        phone: "(41) 3343-2222",
        address: "Avenida Água Verde, 470",
        email: "aguaverde@tintasverginia.com.br",
        timer_title: "Horário de atendimento:",
        timer: "Segunda a Sexta das 08h às 18h <br />Sábado das 08h às 13h",
    },
    {
        name: "Xaxim",
        image: "./assets/stores/store-21.jpg",
        phone: "(41) 3343-2222",
        address: "Avenida Água Verde, 470",
        email: "aguaverde@tintasverginia.com.br",
        timer_title: "Horário de atendimento:",
        timer: "Segunda a Sexta das 08h às 18h <br />Sábado das 08h às 13h",
    },
]
